### ISSUE TITLE
retard  what is this 😂 

### ISSUE THREAD

**Issue by 3arthqua4ke** [Crystallinqq/SnowClient#10]
the title 🤣

**Comment by Crystallinqq** [comment]
Its Snow Client. stop impersonating good developers now

**Comment by 3arthqua4ke** [comment]
How about you learn how to reverse engineer properly 👍 🤪 🤣 😂 🤡

**Comment by Crystallinqq** [comment]
i can reverse fine ❓

**Comment by Crystallinqq** [comment]
all u know is open up class in recaf and decompile 😸

**Comment by 3arthqua4ke** [comment]
you can reverse shit lmaooooo

**Comment by 3arthqua4ke** [comment]
you cant reverse shit lmaooo

**Comment by Crystallinqq** [comment]
ur not good at trolling.

**Comment by 3arthqua4ke** [comment]
ur not good are reverse engineering.
